name: Test1
on: push

jobs:
    run_test:
        name: Running first thing
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.event_name }}
            - run: echo ${{ github.event.ref }}
